// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHzvsEKpDxNi7N-lPIGT5VkNG9UdA-SZE',
    appId: '1:215627660972:web:ec0ec4522d523451a86909',
    messagingSenderId: '215627660972',
    projectId: 'oneclick-026',
    authDomain: 'oneclick-026.firebaseapp.com',
    storageBucket: 'oneclick-026.firebasestorage.app',
    measurementId: 'G-X27RS95QJ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUK5Fci5ifcd3PYoQkT5VMAJmS_Ym8Soo',
    appId: '1:215627660972:android:ca364eb89b9de73ca86909',
    messagingSenderId: '215627660972',
    projectId: 'oneclick-026',
    storageBucket: 'oneclick-026.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY7aofTaYWpadYHrFOh2tXG_mVuNX3msA',
    appId: '1:215627660972:ios:247358ea2652418ba86909',
    messagingSenderId: '215627660972',
    projectId: 'oneclick-026',
    storageBucket: 'oneclick-026.firebasestorage.app',
    iosBundleId: 'com.example.oneclick',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDY7aofTaYWpadYHrFOh2tXG_mVuNX3msA',
    appId: '1:215627660972:ios:247358ea2652418ba86909',
    messagingSenderId: '215627660972',
    projectId: 'oneclick-026',
    storageBucket: 'oneclick-026.firebasestorage.app',
    iosBundleId: 'com.example.oneclick',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHzvsEKpDxNi7N-lPIGT5VkNG9UdA-SZE',
    appId: '1:215627660972:web:de55c6d45bf4e220a86909',
    messagingSenderId: '215627660972',
    projectId: 'oneclick-026',
    authDomain: 'oneclick-026.firebaseapp.com',
    storageBucket: 'oneclick-026.firebasestorage.app',
    measurementId: 'G-017R5FX4XL',
  );
}
